### ISSUE TITLE
V4

### ISSUE THREAD

**Issue by nadavshatz** [gnazarkin/ember-cli-recurly#1]
Hello!

I wanted to know if this addon is being maintained and if there are plans to update it for V4 and the pricing API's ?

**Comment by gnazarkin** [comment]
@nadavshatz I stopped maintaining this add-on a while back (primarily due to not being a Recurly user anymore). Let me know if you are interested in taking over as the maintainer

**Comment by nadavshatz** [comment]
@gnazarkin it might make sense to reduce duplication.

Can I ask why did you stop using Recurly? We are just starting to use them now so it's quite interesting.

**Comment by gnazarkin** [comment]
@nadavshatz I agree. We just moved to a lighter tool as didn't really need a lot of the features from Recurly (we just needed basic subscriptions). Recurly is an amazing service and I would still be using it if there was a need
